// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DEFAULT_URL = 'https://iiqalqmbrtfpcscdhuvi.supabase.co';
const DEFAULT_ANON = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpcWFscW1icnRmcGNzY2RodXZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MTk3OTIsImV4cCI6MjA3MDI5NTc5Mn0.GqzNxKDUguBFidKRY2P6O5dWWnrCs-1eFrB-nKLswBo';

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string | undefined) ?? DEFAULT_URL;
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined) ?? DEFAULT_ANON;

if (!import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_ANON_KEY) {
  console.warn('[Supabase] VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY not set. Falling back to embedded defaults.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});