// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiqalqmbrtfpcscdhuvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpcWFscW1icnRmcGNzY2RodXZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MTk3OTIsImV4cCI6MjA3MDI5NTc5Mn0.GqzNxKDUguBFidKRY2P6O5dWWnrCs-1eFrB-nKLswBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});